### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by diegolirio** [diegolirio/design-rest#2]
#TASKS 
   
- [x] Pagination modelo query
- [ ] Pagination Marca query 
- [x] Pagination Ano query 
- [x] Pagination Ano query 2
- [ ] Acentuacao Geral
- [x] Update Version Pipeline e Deploy
- [x] HttpSTatus 404 para consulta nao encontrada por ID
- [ ] Ordenacao por data
- [ ] Paginacao consulta por Lote, Marca e outros
